name: Merge
"on":
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test --coverage
      - run: yarn build
      - name: Codecov
        uses: codecov/codecov-action@v1.2.1
        with:
          directory: ./coverage
          fail_ci_if_error: true
